# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d4c494705b2a38ff63729dc6006f2327cb61a7fab25f637f6996a828f405baf92b4266f75e6d8468bb75b3c4f9fea381e8883cf8b46636ba4120f3f4482ba6aa

test:
  secret_key_base: ef908544a1aa0e857ba7cebbdd252394a53005ad353284b86a8be8a4a97829088c7a765f59337d44cc243697f09ec119be2d106be335fddb56d51e926c669971

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
